language: generic

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - gfortran
      - libnetcdf-dev
      - libopenmpi-dev

install:
  - "cd .. && 
    git clone --depth 1 --recursive https://github.com/NOAA-GFDL/MOM6-examples &&
    cd MOM6-examples &&
    sed -i \"46i use    fft99_mod, only: fft991, set99\" src/FMS/fft/fft.F90"

script:
  - "mkdir build_release && cd build_release &&
    cmake -DCMAKE_BUILD_TYPE=RELEASE ../../mom6-cmake-build"
  - make -j MOM6
  - make -j MOM6-SIS2-coupled
